### ISSUE TITLE
Several warnings during a simple run

### ISSUE THREAD

**Issue by glihm** [ratschlab/RiboDiff#4]
Dear devs,

thank you for this package, and I hope you'll be able to help me on the warnings I have. I just want to be sure that my results are not affected by these warnings. The setup:

**Python==2.7.12, RiboDiff==0.2.1, scipy==0.19.1, numpy==1.13.3, matplotlib==2.1.0, statsmodels==0.8.0**

0. Pandas warning at the beginning, this one is clearly not impacting the results, but you might be interested in it:
_/.../python2.7/site-packages/statsmodels/compat/**pandas.py**:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead._

1. In the step "Start to estimate raw dispersions":
_/.../python2.7/site-packages/scipy/optimize/**_minimize.py**:600: RuntimeWarning: Method 'bounded' does not support relative tolerance in x; defaulting to absolute tolerance._

2. Fit dispersion: 
_/.../python2.7/site-packages/RiboDiff-0.2.1-py2.7.egg/ribodiff/fitdisp.py:35: RuntimeWarning: invalid value encountered in greater idx = np.logical_and(dispRaw > lowerBound, dispRaw < upperBound).nonzero()[0]
/home/pbertin/venvs/py27/local/lib/python2.7/site-packages/RiboDiff-0.2.1-py2.7.egg/ribodif/fitdisp.py:35: RuntimeWarning: invalid value encountered in less
  idx = np.logical_and(dispRaw > lowerBound, dispRaw < upperBound).nonzero()[0]
/.../python2.7/site-packages/statsmodels/genmod/generalized_linear_model.py:244: DomainWarning: The identity link function does not respect the domain of the Gamma family. DomainWarning)
/.../python2.7/site-packages/RiboDiff-0.2.1-py2.7.egg/ribodiff/fitdisp.py:49: RuntimeWarning: invalid value encountered in less if np.nonzero(dispFitted < 0)[0].size > 0:_

The last warning is the most important to solve I think in the way that I don't want my final values impacted.
My input table respect the format given in the MANUAL, there is not 'NA', only numbers (>= 0) and the first column contains ID of genes without space of weird chars, there are from ENSEMBL: "ENSG00000179919.3"

Thank you very much for you time and this program!

Best,
glihm

**Comment by yizhong** [comment]
Hi glihm,

Thanks for your feedback.

Regarding the first and second points, I don't think you should worry about them. 

The third warning message suggests there may be a few cases (maybe just one gene) where the raw dispersion estimates violate the fitting step. To check if it is a systematic issue, I recommend you to plot a histogram of the p values from the final result table. Something like:
http://genomicsclass.github.io/book/pages/eda_for_highthroughput.html
If you see higher frequency of smaller p-values, then it should be okay. But if you see uniform p-value distribution and you see certain genes are not significant but you know they should, that may indicate a systematic issue. 

I think the format of your input is perfectly good. The warning message here is because some of the read counts result abnormal raw dispersions. Another thing to check is the range of the final dispersions. What's the minimal and maximal? Most of them should be between 0 and 1.

Thanks,
Yi

**Comment by glihm** [comment]
Dear Yizhong,

thank you very much for this answer.

I did what you suggested and you were right. The problem was that some spurious transcript annotation (hg38 human genome version) were violating the fitting step. Removing them, the warning disappeared. Thank you for this advice and the useful link you sent to me. ;)

The minimal and maximal final dispersions are as you mentioned, between 0 and 1 for most of them.

Thank you for you prompt reply and the useful advices!

Best,
glihm

**Comment by brendanwee** [comment]
Dear Devs, 

Thank you for the package. When I ran it, I received several warnings about incorrect values being used in boolean comparisons similar to those listed above:
python2.7/site-packages/RiboDiff-0.2.1-py2.7.egg/ribodiff/fitdisp.py:35: RuntimeWarning: invalid value encountered in greater
  idx = np.logical_and(dispRaw > lowerBound, dispRaw < upperBound).nonzero()[0]

python2.7/site-packages/RiboDiff-0.2.1-py2.7.egg/ribodiff/fitdisp.py:35: RuntimeWarning: invalid value encountered in less
  idx = np.logical_and(dispRaw > lowerBound, dispRaw < upperBound).nonzero()[0]

python2.7/site-packages/statsmodels/genmod/generalized_linear_model.py:302: DomainWarning: The identity link function does not respect the domain of the Gamma family.
  DomainWarning)

python2.7/site-packages/RiboDiff-0.2.1-py2.7.egg/ribodiff/fitdisp.py:49: RuntimeWarning: invalid value encountered in less
  if np.nonzero(dispFitted < 0)[0].size > 0:

My dependencies:
statsmodels version = 0.9.0
scipy version =  1.1.0
numpy version = 1.15.4
python version = 2.7.15
matplotlib version = 2.2.3

Looking at the results, I got a very large amount of NaNs.
There were ~55000 genes in the original data, but only ~18000 came back with numeric p-adj or pvalues. Out of these ~18000 padj, only four are less than .01.

I am unsure what is causing all of these NaNs and am not sure what glihm means by spurious transcript annotations. 

Plotting my p-adj values I get the following distribution:
![ribodiff_padj](https://user-images.githubusercontent.com/22348941/56940722-1f2f7a80-6ade-11e9-9903-b9544f9b6b7a.png)

Do you have any insight on why so many transcripts are coming up as NaN? 
We think it is a bit surprising that only four transcripts are differentially translated. Any help would be greatly appreciated.

Thanks,
Brendan

**Comment by yizhong** [comment]
I suspect the issue is your input data does not follow the model implemented in RiboDiff. Maybe you could describe the details about it? Thanks.

**Comment by brendanwee** [comment]
They are tab separated gene counts, output from STAR after aligning uniquely to the transcriptome. I have two time conditions of RNA_seq and Riboprofiling and 3 replicates each. 
[0_24_gene_counts.txt](https://github.com/ratschlab/RiboDiff/files/3134903/0_24_gene_counts.txt)

**Comment by brendanwee** [comment]
They are gene counts from unique alignments to the transcriptome from STAR. I've attached the file below. After looking more closely at the counts, i suspect that perhaps ~18000 genes have enough reads to calculate a p-value? 
[0_24.txt](https://github.com/ratschlab/RiboDiff/files/3135013/0_24.txt)

**Comment by yizhong** [comment]
It's likely that your data variance across replicates is large. Are they patient samples or something like that? Also, please make PCA plots to see how it looks like. And you could also try to remove duplicated reads from STAR BAM files before run RiboDiff. To avoid mis-aligned reads, maybe more stringent aligning parameters could help (not sure how much it improves your results though). Thanks.

**Comment by brendanwee** [comment]
They are Mice samples, so they shouldn't have much genetic variation. 
Here is the PCA plot, I suppose you mean to measure the variance for each sample?
![replicate_pca_plot_labels](https://user-images.githubusercontent.com/22348941/57157803-b41cc700-6daf-11e9-9134-f949c94ced7b.png)
I am unsure what to make of this plot. It seems like there is a fair amount of variance between MRNA and RPF libraries. Is that unusual?

As for removing duplicated reads, the count files are what a given to RiboDiff as input. STAR counts reads to a gene if the read maps to one and only one gene. So I don't think that is the issue here.

Does ribodiff provide some type of normalization across samples to help handle variance across libraries?

**Comment by yizhong** [comment]
It's hard to see the pca result because you included T72, which seems very spread out. However, I feel your count data is not well clustered by conditions, namely 3 T0 and 3 T24 should fall into separated clusters for Ribo-seq, and the same observation should also appear in your RNA-seq data.

**Comment by brendanwee** [comment]
That makes a lot of sense. Thanks so much for your help!
